### ISSUE TITLE
Number of iteration in minimi for deconv.f (MCS fortran)

### ISSUE THREAD

**Issue by dsluse** [COSMOGRAIL/COSMOULINE#4]
This might not be relevant for COSMOULINE general use but I prefer to mention it anyway. 
The file deconv.f reads the variable itmax from deconv.txt. This parameter fixes the maximum number of iterations for the minimisation. In deconv.f, the corresponding line is:    
`read(4,'(A42,I4)') ligne,itmax`     
This artificially fixes the maximum number of iterations in the minimisation routine to 9999 (but in practice it could rather be 1000). This could be fine in most of the cases, but one could consider to use I6 or I8 to allow larger number of iterations.

**Comment by martin-millon** [comment]
I think in COSMOULIN this is overwritten by what you set in the template_deconv.txt. Usually 2000.

**Comment by dsluse** [comment]
With 2000, no problem. As soon as the value in COSMOULINE is < 9999, there won't be any problem. But if one wants to fix the max number of iteration to a value > 9999, the executable of deconv.f (as available here) will crop the number of minimizations to 4 digits. You can close this issue if this situation has no chance to happen. ;-)
